version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - C:\docker-volume\airnotifier\mongo\db:/data/db
      - C:\docker-volume\airnotifier\mongo\/configdb:/data/configdb
  airnotifier:
    build: .
    ports:
      - 8801:8801
    depends_on:
      - mongo